* fisica
** parciales 20% cada uno
   1, semana 6(28 febrero)
   2, semana 11(18 abril) 
   final, semana 15(30 mayo)
*** contenidos
   25%  punto laboratorio
   50% ejercios o problemas
   25% otras ,variedad
** seguimiento 40%
*** quizes 5% cada uno
    quiz 1, semana 5(14 o 15 febrero)
    quiz 2, semana 9(21 o 22 marzo)
    quiz 3, semana 15(16 o 17 mayo)
*** practicas de laboratorio 15%
**** guia impresa
***** objetivo
***** marco teorico
***** procedimiento
***** evaluacion
      informe (semana siguiente)
      hoja respuestas (ese dia)
*** exposicion 10%
    preinforme o avanse 20%
    nota grupal 20%
    nota individual 50%
    asistencia otras expociones 10%
*** temas exposiciones
**** biomecanica de peces saltadores,
     como arawana, arapaima,salmones,ciclidos
     analisis: vecotorial y cinematico de los peces saltadores
     estudio: pez movimiento del agua y posion de la presa
     en semana 5 preinforme
     en semana 7 exposicion
**** estructura
     que queremos lograr (comunicar)
     abordaje conceptual y teorico
     contenido
     algo experimental
     aplicaciones
     concluciones
     bibliografia y recursos
** recursos del curso
   fisica universitaria,sear,zemansky
** monitorias de 5 piso bloque 38
* clase 1
  que es fisica?
  ciencia que estudia el funcionamiento del todo(universo) y sus partes
* clase 2
** cantidades fisicas
   al realizar mediciones obtenemos numeros que describen fenomenos fisicos, estos numeros los llamamos cantidades fisicas y estas constitullen ese conjunto de constantes y variables que usamos en fisca
** cantidades
*** escalares
    se describen mediante un numero , solo posen magnitud
*** vectoriales
    posen magnitud y direccion
las cantidades nesistan una medida,estas facilitan la comunicacion
se usara el sistema internacional
*** metros
    km=10m³(central)
    hm=10m²(hectometro)
    Dm=10m (decametro)
    m=1m
    dm=10m⁻¹(decimetro)
    cm=10m⁻²
    mm=10⁻³
*** masa
    kg=10g³(central)
    hg=10g²
    Dg=10g
    g=1g
    dg=10g⁻¹
    cg=10⁻²
    mg=10⁻³
*** tiempo
    s=1s(central)
    60s=min
    3600s=hr
*** unidades compuestas
* clase 3
  si los modelos se hacen en metros,funcionan en metros
  la magnitud no puede ser negativa
  los vectores
  lambda es un operador
  λA*-1 =-A
  si lambda es diferente 1 cambia la magnitud
** operar vectores
*** suma
    cabeza con cola
*** resta
    cola con cola
    la resta de A⃗-B⃗
    tienen la misma magnitud, pero con direccion opuesta
    la base en vectores son las dimenciones (no son bases numericas)
    vector unitario es que es magnitud 1
* lab
 todo en una mks?en alguna unidad central
 material
* clase 4
caclular la magnitud del vector
|A⃗|=√(Ax²+Ay²)
hallar la direccion
*** si es en el cuadrante +,+
    θ=tan⁻¹(Ay/Ax)
    θ=∠
*** si es en el cuadrante -,+
θ=tan⁻¹(Ay/Ax)
180°-θ=∠
*** si es en el cuadrante -,-
θ=tan⁻¹(Ay/Ax)
180°+θ=∠

*** si es en el cuadrante +,-
θ=tan⁻¹(Ay/Ax)
360°-θ=∠

meter las cordenadas en postivo independiente del cuadrante,

*** producto escalar,producto punto o producto interno son la misma cosa

|A⃗||B⃗| cos θ
θ es el angulo entre los 2 vectores
si los vectores estan el la misma direccion no hay que hacer coseno
cuando los vectores son perpendiculares da 0

* clase 5

 
**  producto vectorial
i|j|k
-+-+-
Ax|Ay|Az
-+-+-+
Bx|By|Bz
opere en x
ejemplo

i+j+k



** cinematica ,
   lo que estudia el movimiento, no estidia que causo que se moviera

*** posicion
    una cantidad vectorial dada por la ubicacion referente a un origen , de un sistema cordenado

*** movimiento unidireccional
    es una cantida ,cuando la velocidad es constante se puede ver de fomra lineal

* clase 7
  protyectiles

  es un movimiento rectilinio uniforme en el eje horizontal y movimiento unifome acelerado en el eje verical

  la velocidad es bidimencional

  se analisa cada eje de forma independiente

  un proyectil es una caida libre con movimento lateral

  formulas:

  https://apirepo.cubaeduca.cu/v1/private/60-1f47ungjs/11-10Proyectiles/res/0-ec_proyectiles.png

  (para el parcial se puede traer formulas)

* clase 8
  mru formula

  x=x0+vxt

  mua

  y=y0+vy0t+(1/2)*g*t²

  libro, capitulo 3 movimiento en 3 dimenciones

* clase 9

  
** fuerza de friccion

   es mas dificil empesar a mover algo que mantener moviendo ese algo

   en un cuerpo en reposo no hay friccion

   leyes de newton

   1 un cuerpo permanece en reposo hasta que una fueza externa actue en el

   2 la fuerza es masa por aceleracion , m*a

   
* clase 10
** dinamica del movimiento circular

   semejansa de triangulos

(Δv/v1)=(Δx/r1)

Δv=Δx*(v1/r1)

aceleracion centrifuga o radial

ar=(v²/R)

(ar es aceleracion radial)

la friccion de un carro al tomar una curva donde puede derrapar ,es hacia adentro de la curva

la friccion es la que no salirse de la curva al carro
**** 

  F fuerza,

  fs fuerza friccion,

  m masa

  g gravedad, 9.8

  v velocidad

  R radio

  N fuerza normal
  
**** formulas

  ∑F=max

  ∑Fx=max

  fs=max

  fs=(mv²/R)

  ∑Fy=0

  n-w=0

  n=mg

  la curva no afecta la componente en y, ni por que este inclidada.

  Nx=mar

  Nsen(β) =(mv²/R)

  Ncos(β)=mg

  cos(β)=(mg)/N

  V²>gR

  V> sqrt(gR)

para que halla fuerza normal tiene que estar en el piso(contacto), si la fuerza normal es 0 por que esta callendo.

* clases
** trabajo con resortes
  fuerza para deformar el resorte F=kx
analsisi grafico
wf=area + area
wf=(x2-x1)kx+1/2(x2-x1)(kx2-kx)
wf=kx1x2-kx²1+1/2kx²2-1/2kx1x2-17/2kx1x2+1/2kx²1
wf=1/2kf2
** energia potencial
   Ug=mgy
  
** pregunta proximo lab
   como se relaciona el cambio de energia con el trabajo
   
** ejercios
   parcial dentro de 15 dias
   5.58
   5.72
   5.73
   5.68
   5.89
   5.91
   5.92
   5.93
   5.94
   5.99
   5.103
   5.120
   ejercio de resortes
   7.43
   7.38
   7.41
   7.42
   7.45
   7.47
   7.49
   7.50
   7.55
   7.65
   7.75
   
** energia potencia elastica
   (1/2)ks²
   ΔUels=(1/2)kx²1 -(1/2)kx²2
   trabajo positivo saca energia
   trabajo negativo almacena energia
   
** cantidad de movimiento lineal
   es una cantidad de movimiento lineal que tiene un sistema
   el momento total del sistema es la suma de los momentos individuales de cada cuerpo 

   momento (p)
   m masa
   velocidad
   P=m*v
   cada vez que hay interacciones se van a ejercer fuerzas entre los participantes de esas interacciones
   esta ley es universal, ocurre desde el mundo micro al macro

   estas fuerzas tienen la misma magnitud y diferente direcciones

   el momento de un sistema se mantiene,pueden cambiar los momentos indiduale, pero no el momento total.
   
** coliciones
   es cuando hay contacto entre cuerpos
* temas (off-topic)
  unidades de medida
  vectores
  mru y mua
  proyectiles
  
  leyes de newton
  dinamica movimiento circular
