* primera tarea
** Calcular el área y perímetro de un triángulo. Calcular el costo real de un paquete turístico, el total pagado por IVA y el descuento obtenido que es el 5% después de IVA. Calcular el costo de un predial que equivale a la milésima parte del valor de la propiedad y tiene un descuento del 12% si se paga antes de una fecha estipulada. Calcular el salario neto y descuento préstamo de un empleado que gana un salario base y un porcentaje de las ventas y se le descuenta la seguridad social y un 7% para un préstamo que tiene con la empresa. 
* 1 plantarse el problema
** primero dividir el problema en partes
*** area y perimetro
*** costo de un paquete turistico
*** 
** input
*** (int para evaluarlos en la unidad de medida mas pequeña ya sea milimetros , centavos ... en este caso que son cosas que se pueden contar)
*** unsigned short int alturatriangulo = input() # altura base triangulo
*** unsigned short int basetriangulo = input() # base del triangulo
*** unsigned short int costo = input()  #costo del paquete turistico
*** unsigned char	descuento = int(input() /100)+1
** constantes 
*** iva de ese año
* 2- 5/08/2020
* 4- 12/08/2020
** miercoles 6-7pm
** viernes 6am
** al parecer serian las asesorias por google meets
** correo del docente mlopez@udem.edu.co
** temas de programacion orientada a objetos
*** abstractos
*** encapsulamineto
*** herencia
*** polimorfismo
* actvidad "hacer cuenta huevos"
** ... mi cuenta guevos
* 19/08/2020
** diagrama de clases 
*** descripcion
*** es un cuadro con 1 columna y 3 filas 
**** fila 1: nombre de la clase
**** fila 2: variables o atributos(atributos en este caso por ser progrmacion orientada a objetos)
***** los atributos se puenden declaran identificar de atributo:tipo de dato
**** fila 3: funciones o metodos (metodos en este caso por ser progrmacion orintada a obejos)
***** no se nesita siempre el metodo init
***** los metodos se pueden declaran metodo(si hay paremteros ,si existen mas parametros):si retorna algo poner el tipo de dato que retorna 
** diferenciar para esta clase entre  progrmacion  orientada a objetos y orientada a procedimientos  
** star uml herramienta libre para hacer el mapa de clases
** ejercio : 1) Se solicita calcular la edad mayor y menor, entre las edades de Hugo, paco y Luis; sus edades son diferentes. Se requiere calcular el valor del pago para un empleado que tiene un salario base y bonificación por ventas del 2%, se debe retener el 8% para seguridad social y si el devengado excede 3 millones el 1% como retención y finalmente mostrar los datos calculados.3) Se tiene una planta con los atributos color, altura y florece, se requiere modelarla en Python, de forma que se pueda averiguar si florece y mostrar sus atributos color y altura. 
** ejercio 1)
*** nombre clase
**** diferenciaEdad
*** atributos
**** edadhugo:int
**** edadpaco:int
**** edadluis:int
*** metodos
**** init(int,int,int)
**** mayor():str,int
**** menor():str,int
** ejercio 2)
*** nombre clase
**** relacionadoAlEmpleo
*** se acabo la clase
** ejercio 3)
*** nombre clase
**** AveriguarLeCosasAlgunaPlanta
*** atributos 
**** color:int
**** florese:bool
**** altura:int
*** metodos
**** init(bool,int,int)
**** siFlorese()
**** descripcion():array
* 24/08/2020
** no hubo clase debido a que zoom no funcionava se intento en teams y no era muy amigable , honesta con linux ,teams y zoom por lo que visto funcionan mejor optimisadas y hay mas soluciones para los errores y la coneccion/interacion en windows
* 26/08/2020
** ejercio
*** Se requiere calcular el valor del pago y cada uno de los descuentos realizados a un empleado, que gana un salario base y porcentaje de ventas así: • Propiedad raíz 1% • Vehículos 2% • Mercancías 5% También se requiere conocer el valor devengado por tipo de venta. El empleado tiene los siguientes descuento variables • Seguridad social • Prestamos • Fondo de empleados Tenga en cuenta que al empleado se le hace una retención sobre el devengado según la siguiente tabla. • Inferior a 3 millones 0% • De 3 a 5 mil 1% • De 5 a 8 mil 3% • De 8 a 12 mil 5% • Superiores a 12 mil 8% Nota: todos los descuentos se hacen sobre el devengado. Se requiere crear un programa que permita matricular un usuario en una página web, pudiendo darse de alta, inhabilitarse, habilitarse, cambiar contraseña y retirarse. Se requiere gestionar el servicio que se le presta en un centro de lubricación los vehículos para generarles la factura; se manejan los siguientes datos Placa tipo de vehículo y capacidad de aceite, fecha del servicio 
*** hacer el primero
* 31/08/2020
** uml define el funcionamiento y componentes de un sistema
** ejercio Se requiere gestionar el servicio que se le presta en un centro de lubricación los vehículos para generarles la factura; se manejan los siguientes datos Placa tipo de vehículo y capacidad de aceite, fecha del servicio, precio del litro de aceite y un indicativo si el vehículo llega por primera vez o repite servicio; si repite servicio recibe un descuento del 5% sobre el costo del aceite. Al final debe imprimir los datos del vehículo, fecha, costo de servicio, cantidad de aceite gastado y que descuento recibió. 
* 02/09/2020
** hacer un pagina parecida a cuevana para ver peliculas
* 07/09/2020
