* calculo
se va a tarbajar con el libro de stewart
** 1 . cuatro maneras de representar una funcion
*** introducir una grafica un graficador
*** dominio 
**** un conjunto de partida
*** rango
**** el rango depende del domino
*** interpretar grafia¿?
** 1)ejercios
*** -2+3
1
*** -(2-3)
1
*** 1/2-1
((1*1)+(2*-1))/2*1
1(-2)/2
-1/2
*** 2a+4b
2(a+2b)
*** -2(-3-5)
-2(-8)
16
*** -2²
4
*** (-2)²
-4
*** √(4²+3²)
25
*** (√4²+√3²)²
(4+3)²
49
*** (-1/2)-2
((-1*1)+(2*-2))/2*1
(-1+-4)/2
-5/2
*** -(3/2)-(5/3)
((3*3)+(2*5))/(3*2)
(9+10)/6
19/6
*** -(-4/6-4/2)²
-(4*2-6*4/(6*2))²
-(8 - 24/12)²
-(16/12)²
(16²/12²) = 256/144
256/2 y 144/2 = 128 y 72  , 64 y 36 , 32 y 18 ,16/9...
-16/9
*** (1/2-1/3)⁻¹
((1*3)-(2*1))/2*3
(3-2)/6
(1/6)⁻¹
1/(1/6) ;1*6/1*1 =
6
** 2) rescribir las ecuaciones de tal forma que el signo menos sea un factor comun
*** a) a+b
a+b
*** b) -3a+9a²b
-3a(3ab)
*** c)-4a-12abc
4a(-1-3bc)
*** d) 1/2-2/3
*** e)(-2-3)³
(-5)³
-5*-5*-5=-125
*** f)-(-1)²d+(-1)³c
-1d-1c
** 3) escibir 3 numeros reales entre otros 2 dados
*** a)0 y 0.5
1/8  , 0.125
1/10 , 0.01
2/5 , 0.4
*** b)-1 y 0
-0.2
-0.999999
1/-φ
*** c)0.1 y 0.2

(√2)/100
(√3)/100
0.03
*** d) 1/2 y 1/3
2/5 ,0,4
7/17
6/16
*** e) -(1/3) y -(1/2)
-6/17 , -0.35...
-7/18 , -0.388..
-8/19 , -0,4210.
*** 4/3 y 11/4
φ = 1.618033
e =  2.71828
π/2 = 1.570796326795
** 4) de una conclusion de elevar por 1,2,3,4 y 5 estos numeros
*** a) (-1)^n
genera un ciclo entre 1 y -1 
*** b) (0.1)^n
mientras el exponente se aleje de 1 , mas partes puede tener y ser mas cercano a 0
*** c) (1.1)^n
incrementa sus decimales y tambien sus enteros 
*** d) (-0.1)^n
genera un ciclo entre positivos y negativos , los exponentes pares tienen el signo menos y los impares los negativos , esto mientras se hacerca a 0 y incrementan los decimales
*** e) -(1.1)^n
se va aumentado los enteros y la cantidad de decimales , hay mas decimales que se aprocciman a 0 .
*** f) (0.1)⁻n
todos son numeros con un exponente mayor o igual a 2 , me dieron 9 , como si fueran multiplicados de 10 en 10 pero: 99,999,9999 
*** g) (1.1)⁻n
el numero resultante va llegando mas a 0
*** h) -0.1⁻n
da como el f , con solo 9 con exponentes mayores o iguales a 2,pero con negativos
*** i) -1.1⁻n
mayor expoente , mas se acerca a 0
** realizar
*** a) 1/2+1/3
(3+2)/6
5/6
*** b) 3(3/2+1/3)
(9+2)/6
3(11/6)
33/6
*** c) 3/4*3/2*1/3
9/8*1/3
9/24
*** d) 3/4((3/2)/(1/3))
3/4(9/2)
27/8
*** e)3/5(1/2-2/3)²
 (1/2-2/3) , 1*3-2*2/3*2
 (3-4)/6
 (1/6)²
 1/36
 3/5*1/36
 3/180
*** f) (3+1/2)/(2-1/3)
3/1+1/2 , (3*2+1*1)/1*2 , (6+1)/2 , 7/2
2/1-1/3 , (2*3-1*1)/1*3 , (6-1)/3 , 5/3
7/2/5/3
21/10
** distancia entre puntos en el plano cartesianos
*** p0 (-1,-1) y p(2,3)
√((-1-2)²+(-1-3)²)
√(9 + 16)
√25
5
** desigualdades ,ecuaciones y inecuaciones
*** dos menor que tres
2<3
*** raiz cuadrada de 2 es menor que raiz cubica de 27
1.41.. < 3
*** 2x -3 = 4x+2
 -2-3 = -2x+4x
 5 = 2x
5/2 = x
*** (x/2)+3 = x/3-2
(x/2)-(x/3) =-3-2
(3x-2x)/6=5
x/6 =5
x=5*6
30
*** x/2+3= 3/x-2
 x/2-3/x=-5
 x²-6/2x = -5
*** 2x-3 > 4x +2
 2x-4x>-5
 -2x>5
 x<5/-2
*** x/2+x > x/3-2
    x+x/2+x/3>-2
    x(1/1+1/2+1/3)/6>-2
    x(6+3+2/6)>-2
    11x/6>-2
    x>(-2/11)*6
    x>-12/11
*** el triple de un numero es el cuadrado de otro numero
    3x = y²
*** la mitad del dinero de juan es el doble del dinero que tiene pascual
    x/2 = 2y
** practicar parcial
   780 dolares para 50 apartamentos
   790 dolares para 30 apartamentos
   m = (50-30)/(780-790) , =-2
   b = se halla despajndo

   x = 5
   y = 
   2  m =
** stewar
*** (-3)⁴
-3*-3*-3*-3
81
*** -3⁴
    -81
*** 3-⁴
(1/3)*(1/3)*(1/3)*(1/3)
(1/81)
0.012345679012345678
*** 5²³/5²¹
    5²
    25
*** (2/3)-²
    (3/2)*(3/2)
*** determine el tipo de funcion (solo respuestas para optimisacion de tiempo)
    
*** x²
cuadratica
*** √x-1
radical
*** cos()...
trigonometrica
*** 2x²+3x+4
identidad
*** punto (-2,-2 ) m = 0
donde puedo poner -2 ,-2
y-y1=(y2-y1)/(x2-x1)(x-x1)
m = 0 ()
** taller 6
(grafica no disponible)
f(-3)=2 
f(-2)=1
f(3)=indefinido
f(-1)
3
1
5
7
** parte taller 8
** parcial2
*** 1,2,3,4,5
 (7x-2)(x+1)/(49x²-4)
 (7x-2)(x+1)/(7x+2)(7x-2)
** preguntas ¿?
*** 2a+4b ¿se puede simplificar? 
2(a+2b)
*** que hace que el resultado de -2² sea diferente a (-2)² 
because -2² means -(2²). (there's not much of a reason for *that*, except that it's convenient.) , by buster. -2² != (-2)² = (-2)*(-2)
*** en el ejercio 2 de rescribir las expresiones para que - sea un factor ¿en algunos no se puede por que no hay -?
** 3 veces preguntado , respuesta de irc.libera.chat:6667 #math
*** a+b puede tener - como factor comun?
*** 1/2-2/3 , una fraccion como se puede factorisar , pienso que quedaria 
** las embarradas
*** para caclular m se usa (y1-y2)/(x1-x2)
* referencias 
[[https://web.ma.utexas.edu/users/m408n/CurrentWeb/LM0-0-1.php][ruta del calculo]]
[[https://mind42.com/public/f73df552-1104-4053-848e-2b5baad8bbbe][mapa jerarquico del calculo]]


* curso
quiz cada semana
** notas
  1 parcial (15%) 4 semana (virtual)
  2 parcial (17%) 8 semana (virtual)
  3 parcial (25%) 12 semana (presencial)
  final (27%) 17 semana (presencial)
  16 quizes,16%
* ejercios
*** x/2 + x = x/3 −2
    x/2-x/3+x=-2
    5x/6+x=-2
    11x/6=-2
    
*** x/2 + 3 = x/3 −2x
   3=-x/2+x/3-2x
   x/2+x/3-2x
   5x/6-2x/1
   3=17x/2x
   
*** x/2 + 3 = 3x −2
    x/2-3x=-3-2
    x/2-3x=-5
    x+6x/2=-5
    7x/2=-5
    
*** 2/x + 3 = x/3 −2
    2/x-x/3=-5
    5+x/3x=-3

*** x/2 + 3 = x/3 −2
   x/2-x/3=-5
   x3-x2/6
   x/6

*** 2x −3 = 4x + 2
    -2x=5
   
** 1.10     
*** x/2 + 3 < x/3−2x
    3x/2 +2x-x/3< -3
    x/2+2x/1-x/3
    x*1+2*2x/2=5x/2
    5x/2-x/3, 5x*3-2*x/2*3,13x/6
13x/6<-3

*** x/2 + x > x/3 −2
    x/2+x/1-x/3>-2
    x+2x/2
    3x/2
    3x/2-x/3
    9x-2x/6
    7x/6>-2

*** x/2 + 3 ≥ 3/x −2
    x/2-3/x >= -3-2
    -6-2x/2x>= -5

*** 2/x + 3 ≤ x/3 −2
    2/x-x/3 <= -3-2
    2x-3x/3x<=-5
    -x/3x<=-5

*** x/2 + 3 < x/3 −2
    x/2-x/3 < -3-2
    -6-2x/2x < -5

*** 2x −3 > 4x + 2
    2x-4x>5
    -2x>5

*** a) (a + b)2 6= a2 + b2 y en general para cualquier exponente.
  no hay igualdad por en un caso primero se suma y luego se exponencia todo junto y en el otro se exponencia y luego se suma, en este caso el orden de los factores afecta el producto
***   √a + b 6= √a + √b y en general para cualquier  ́ındice de la ra ́ız.
   el orden de los factores afecta el producto,y en este caso no hay una igualdad o algo reversible.
   no hay una potenciacion que invalide la raiz
*** √(a2 + b2) = a + b
se potencian y se suman ,se hace la operacion contraria al ser otro numero por que se sumaron
*** -2² != 4
    puede ser si primero se potencia todo inluyendo el negativo,-2*-2=4,como no se potencia el negagativo, este solo multiplica seria -(2*2)=-4
*** (−a + b)/(c)= (−a + b)/(c)
    el resultado cambia por la cantidad de operaciones
*** a/(b + c) = (a/b) + (a/c)
en una parte se dividen 2 cosas , en la otra se divide 1 , 
* taller 2
  es o no es funcion
  1 no , es una accion que no involucra numeros, a menos que descuente de un valor  
  2 no, no es cuantitativo
  3 si, por que toma un valor externo (valor petroleo) y lo observa en el tiempo
  4 si, pero nesesita tener valores numericos
  5 no,(imaginando que no hacen referencia a numeros primos)
  6 si , por que la formula de velocidad proviene del calculo 
  7 no, es una constante y en calculo seria mas una relacion
** determinar funciones apartir de tablas
   f(), si
   g(), si
   w(), si
   h(), si
   T(), no ,se repiten valores
   M(), no ,se repiten valores
que quiere decir Df y Rf en el punto  1.4
c)1.2...
d)
*
** monitorias
   dominio en x
   rango en y
*
* taller 3
  que tipo de funcion es
*** x²
  cuadrada
*** √(x-1)
    raiz cuadrada
*** cos(x −1) + x
trigonometrica
*** 2x2 + 3x + 4
    polinomica
*** x⁻³
    racional , por que un numero elevado a un negativo ,a⁻n = 1/(a**n) 
* algun momento
**   recta tangente
   linea recta que toca a un solo punto

   una liena que toque una curva en mas de un punto es una recta secante

   Δx≠x
** definicion de la derivada 
lim   fx(x+h)-f(x)
      ------------
Δx→0       h
*** dan
    funcion
    valor en x
*** pasos 
   primero remplaso x con el valor del dado
   resuelve la operacion
   remplasa h o Δx por 0
** temas
   derivada de fraciones
   trigonome tricas
   regla de la cadena
   logaritmos
