
* actividad
** con 3 textos dar la siguiente informacion 
*** titulo
*** formato
*** parrafo introcuctorio
*** caracteristicas
*** link
** texto 1
*** titulo:Voyant Tools redme.md
*** formato:instructivo
*** parrafo introductorio
    Voyant Tools is a web-based text analysis, reading and visualization environment. Developed by a small team of digital humanities scholars led by Stéfan Sinclair and Geoffrey Rockwell, Voyant Tools is designed for a very wide range of applications and users, from students to researchers and journalists to market analysts. It strives to balance user-friendliness with a range of analytic and interpretive functions.    
*** caracteristicas
en el texo sale directamente cacteristicas, pero son del programa

las caracteristicas del texto : descriptivo ,informativo(dice quienes lo hicieron y para que) y digital

*** link:https://github.com/voyanttools/Voyant
** texto 2
*** titulo:manfiesto hacker
*** formato:manifesto
*** parrafo introductorio
    Another one got caught today, it's all over the papers.  "Teenager
Arrested in Computer Crime Scandal", "Hacker Arrested after Bank Tampering"...
        Damn kids.  They're all alike.
*** caracteristicas:
    narrativo (cuenta la historia de que arrestan no-hackers, nos damos cuenta que arrestan a no-hackers con lo que dice despues)
    publicitario se quiere vender la idea de que el hacker no es malo
    informativo , enseña lo que no es un hacker (pero no enseña lo que es)
*** link:http://www.phrack.org/issues/7/3.html
** texto 3
*** titulo:Cuando todo el mundo hace algo ...

*** formato: entrada en un blog y opinion
*** parrafo introductorio:
    
No quiere decir que sea lo correcto. Escucha a tu conciencia. No te dejes llevar por la "actualidad". Se firme. Haz de nuestro planeta, un lugar mejor. Cueste lo que cueste. El premio no es otro, que el respeto de quien de verdad importa. Tú. Y de toda la gente, que aún está despierta.
*** caracteristicas:
    expositivo
    Humanístico
    expresa algo
*** link:https://03c8.net/blog_es.php
