* comparatives

use that for them

for say general comparation (superlative) use

some is the <comparative>

we can say

programing is the best


for specific comparation use comparative like

movies are better that series

** home work

*** procinema
ticket 10 000
choclate 3.700
medium pop corn 15.900
big soda 9.500
nachos 1200

*** cinemark
ticket
2d 12.000
Xd 23.000

29.800 pop corn and big soda
12.500 nachos

*** cine colombia
combo 

*** royal films


atachment 1

 3 razon for go to cinema

ticket expencive

1 no very busy
2 ticket are  unexpencive


1 someone invite me
2 i win the ticket
3 someone gift me a ticket

2 how much is a ticket

expencive
//for me free

3 how much is a drink and some popcorn and snack?

10 dolars

4 differences between thtat cinema and our local cinmea?




** day of death in mexico

*** when
 1 and 2 of novermber , 1 is day for kids and 2 is for adults

*** what

is a way to face the dead and the deceased

the second day we have a passage betewn live 
*** how

they wear customs, go  cementeries at night, eat good food have a lot of 

*** why

** questions
Have you ever changed your appearance a lot in a short time? 
Have you ever driven a truck?
Have you ever gone mountain climbing? 
Have you ever met a celebrity? 
Have you ever played a joke on one of your teachers?


Have you ever ridden a horse? 
Have you ever slept in a tent?
Have you ever swum in the ocean?
Have you ever talked to a famous person?
Have you ever been on the radio or television? 
Have you ever been in a fist fight? 
Have you ever broken a bone? 
Have you ever dreamt of a ghost being in your bedroom and then waking up and finding yourself looking around for the ghost?


Have you ever driven a truck?
Have you ever met a celebrity? 
Have you ever talked to a famous person?
Have you ever been in a fist fight?

Have you ever talked "baby-talk" to your pet?  

http://iteslj.org/questions/haveyou.html

** exam

- have you ever ridden a horse

- yes i have

- how do you feel when you ride a horse

- it is relaxing

  have you ever swum in the ocean?

- yes i have, i was swim in pacific ocean , when i was learning diving

- have you ever swum in atlantic ocean

- No i have never swum in atlantic ocean

- you swum in pacific ocen of colombia?

- yes, next to bahia solano

- do you have children

-  yes i have 2 daugthers

-  do you see the screen

-  yes i do

  have thought to have a childrens

 - yes, i like to have childrens and a big famili but not blod familiy

 - why didnt you have not blod familiy  ?

 - a big blod family is very expensive

 - have your even eaten greek food

   i havent , because i havent been in greek

 - in medellin do have the oportunity to visit greek restauruants , why dont you take the oportunity?

- i dont know greeks restaurants

  which greeks restaurants did you know?

  - a polaris restaurant

  - where is it located ?

  - that restauran is located in provensa neighbourhood

    have you ever visited provensa?

  - yes,i was visited provensa not very often

  -  what kind of food do you like?

    i like a loot pizza of 15lukas restaurant?

    - is that the name of the restaurant?

      yes it is called 15lukas because it is located in 15th street in san lucas neighbourhood

      - why do you prefer pizza ?

 - it is delicious

-   do you like pizza ?

   yes i like it

- have you ever tasted pizza in grece?

  no, because polaris restaurant is in medellin

 -  have you been in  grece?

   no, i have never visited grece , but i like this kind of food

   what other food do you prefer diferent to pizza?

- i like a lot ice cream and chocolate

  have you been in other country?

  yes i have been in canada and brasil

-  how was the food in canada?
  
 canadian people prepare a lot of steak

 it is true the like a lot mapple syrup?

 yes they like because is the typcal food

 - how was the food in brasil?

   the prepare a similar food that in colombia , like feijoada it is like a bandeja paise and a coctel kaipiriña it is a mix between tequila and cachasa

  have you ever visited other countries?

  i visited usa when i was a kid and i was last yeard to dominican republic i will go to germany this year to present a bionformatic proyect

  what is bioinformatics?

  bioinfomatics is a displine that merge computer science and genomics, you can edit genes of a plants animalas for something, and i like a other similar disipline that is biohacking

  i make a proyect to remove plages with frogs in my house

-  why do you think this disipline is important for the science?

  is the new computer science in natural of life, you dont code machines, you code life

  how much money did spend to when you went germany?

  i dont know, i have to go, i have never been in germany

  
