* _¿Cómo le parecieron las clases?
** mejores que muchas otras debido a que se lograban hacer didacticas muchas activades que no es comun ver las de manera didcatica y remota 
* _¿Qué aprendió de esta experiencia?
** siempre van  haber cosas que nos van a sacar de la zona de confort y eso es normal y en basquetball obtube un mejor orden a la hora de jugar 
* _¿Cree Usted que lo aprendido le pueda servir para su vida?
** SI debdio a que es un concepto muy aplicable y va muy ligado a la respuesta anterior por que  no sabemos si va volver a pasar de esa magnitud o algo menor como una interruipcion o algo mayor como un pandemia o una guerra
* _¿Considera Usted que con lo visto en clases, está en condiciones de orientar un Calentamiento, entrenamiento o partido?
** depende a quien y el conocimiento que tenga
* _¿Cree Usted que al haber escogido la materia Baloncesto como Deporte, esto le servirá para seguir practicándolo?
** si por eso la escogi para mejorar las bases para seguirla practicando 
* _¿Qué opinión le merece el haber tenido LA SOLIDARIDAD como propuesta de valor institucional en la materia?
** yo creo que eso seria muy valioso  podria servir para repartir conocimiento y generar nuevas habilidaes
* _Le ayudaron las clases a ser una persona mas abierta y entregada a los demás
** si ,cuado se aprende algo muchas personas quieren reproducirlo ,otras quieren guardarlo pero a mi me gusta reporducirlo 
