* preguntas
para uds esta bien o mal consumir drogras?
uds ve que sea correcto que regulen las drogas?
dejaria que un tema que "solo" afecta al que consume, lo administre el consumidor? 
ve algun problema con consumir drogas?

* que son cultivos ilicitos
** definir ilicitos
*** "No permitido legal o moralmente."https://dle.rae.es/il%C3%ADcito
** como definir "cultivos ilicitos"
   (se parte de la base que sabemos que son ilicitos)
   es un cultivo que va encotra de las leyes.
** como afectan?
*** a un territorio
    * deforestacion
      ", Entre Noviembre 2001 y Diciembre
 del 2002, se perdieron aproximadamente 35.000 has, de bosque primario por el
 establecimiento de cultivos de coca y 14.000 has de bosque secundario por la
 misma causa en todo el territorio nacional"[1]
    * la biodiversidad
    * genera desechos quimicos
      ... durante el proceso de conversion de la hoja de coca a cocaina
    * contribulle a la escases de alimentos
      ... el area que antes se usaba para sembrar vegtales o criar ganado, ahora se usa para cultivos ilicitos
    * empeora el calentamiento global
      ... en el proceso del cultivo talan especies tropicales importantes y quemas que desequilibran la atmosfera  , para obetener mas espacio para la siembra
*** a la sociedad
** por que son ilicitos?
   por el impacto negativo es mayor al positivo
* referencia
  http://www.mamacoca.org/docs_de_base/Fumigas/DNE_cultivosIlicitosColombia_.pdf
