libro de las revelaciones
* título de la historia 
** (por cada parrafo critica )la correspondiente parafrásis y crítica
* proyecto resusrreccion
** Pag.1, parrafo uno
*** los ojos permiten dar claridad de la situación.
*** Vemos con los ojos y el cerebro sabe que ve.
** Pag. 1, parrafo 2
*** No depende de un tipo de persona sinó del momento.
** Pag. 1, parrafo 3
*** Muy dificil de explicar pero algunas sustancias en el cerebro causan eso. 
** Pag. 2, parrafo 1
*** Puede que se recree en la mente con una forma u aspecto del ADN ya estructuarado (ADN como forma de recolectar información de seres vivos) 
** Pag. 2, parrafo 2
*** Pero que van a captar con una camara si se habló de algo que no se sabe percibir.
** Pag. 2, parrafo 3
*** 
** Pags. 2 y 3
*** Cada persona recuerda lo que conoce, como dice nadie sabe como  intentar resolver esta situación desde la ciencia, es muy complicado y se necesita de muchas disciplinas para llegar a una aproximación de la solución.}
* Proyecto Persephone
** Pag. 24, parrafo 1
*** No hace falta ser cientifico para darse cuenta del impacto que causa en la población existente.  Hay soluciones para todos los nacimientos.
** Pag. 24, parrafo 2
*** La pandemia el hoy y un mañana están en una crisis

