libro de las revelaciones
* título de la historia 
** (por cada parrafo critica )la correspondiente parafrásis y crítica
* proyecto resusrreccion
** Pag.1, parrafo uno
*** los ojos permiten dar claridad de la situación.
*** Vemos con los ojos y el cerebro sabe que ve.
** Pag. 1, parrafo 2
*** No depende de un tipo de persona sinó del momento.
** Pag. 1, parrafo 3
*** Muy dificil de explicar pero algunas sustancias en el cerebro causan eso. 
** Pag. 2, parrafo 1
*** Puede que se recree en la mente con una forma u aspecto del ADN ya estructuarado (ADN como forma de recolectar información de seres vivos) 
** Pag. 2, parrafo 2
*** Pero que van a captar con una camara si se habló de algo que no se sabe percibir.
** Pag. 2, parrafo 3
*** 
** Pags. 2 y 3
*** Cada persona recuerda lo que conoce, como dice nadie sabe como  intentar resolver esta situación desde la ciencia, es muy complicado y se necesita de muchas disciplinas para llegar a una aproximación de la solución.}
* Proyecto Persephone
** Pag. 24, parrafo 1
*** No hace falta ser cientifico para darse cuenta del impacto que causa en la población existente.  Hay soluciones para todos los nacimientos.
** Pag. 24, parrafo 2
*** La pandemia el hoy y un mañana están en una crisis
** Pag, 24,parrafo 3
*** La solución hoy y el problema mañana.
** Pags 24 y 25
*** Un gran alimento para esta guerra (Siria)  es el petroleo que se podria reemplazar con agua salada para generar hidrógeno y generar combustión.  El petroleo y el hidrogeno existen hace mucho tiempo, pero el hidrogeno como forma de combustión ha sido arrasado por el monopolio del petroleo y esto sería muy accesible ya que agua hay en todas partes y no se necesitaría del agua para sacar combustible porque el agua es el combustible (de donde se saca el hidrogeno)
** Pag. 25 parrafo 1
*** Que " triste"  que se sepa que un sistema de gobierno no sirve debido a esto, si se hacen unos protocolos o código de conducta  sería posible un sistema de anarquía parecido al que usamos actualmente llamado internet.
** Pag. 25 parrafo 2
*** Eso llegaría a su fin si existiera un sistema de anarquía y no existieran las clases, por que la responsabilidad cae en uno y de uno depende si se salva o no se salva.
** Pag. 25 parrafo 3
*** Pero si se acaban los materiales todo tiene un principio y un final, nada dura para siempre y todo se desgasta. Yo pienso que las personas que deberian ir en la nave son las personas que crearon el invento o decicir quien va en la nave.
** Pag. 26 parrafo 1
*** Se complementó con lo anterior
* PROYECTO MKNAOMI
** Pag. 27 parrafo 1
*** Las creencias o suposiciones son un posible acierto, pero si creemos en una suposición no es un acierto, es una creencia, no es una realidad
** Pag. 27 parrafo 2
*** Sin miedo no hay limites, sin limites no hay control , sin control no hay miedo https://03c8.net/dkdf.php.
** Pag. 27 parrafo 3
*** La cuestion con un problema de esos es la solución por lo incontrolable, no sabe cuando detener un problema como esos
** Pag, 27 y 28
*** La indemnización a la familia fue para compensar (valor) valor ficticio y dicen una fuerte suma de dinero, entoces volvimos a la esclvitud que podemos pagar humanos.
** Pag. 28 parrafo 2
*** Condiciones o castigos que no se pueden comprender o darles una razon.
** Pag. 28 parrafo 3
*** Creía que con una consecuencia iba a ser mas efectivo.
** Pag. 28 parrafo 4
*** El conocimiento se desmuestra con otro conocimiento eso solomente afectara a los que no se logren creear ideas propias. 
** Pag. 28 y 29
*** Los que se rebelan, los creen locos o terroristas y en algunos casos intentan defender su ideal con algo que creó esta sociedad, los derechos
* PROYECTO JEDI
** pag. 30 parrafo 1
*** Un hecho, solo caben opiniones.
** Pag. 30 parrafo 2
*** Si mientes mas obediente, mas ilusión, mas creencia y poca inteligencia.
** Pag. 30 parrafo 3
*** En vez de dar presupuesto deberian distribuir la plata y los bienes del estado a cada uno
** Pag. 30 y 31
*** Supongo que hace referencia a las miradas intimidantes que no solo es mirarlo fijamente
** Pag. 31 parrafo 2
*** Cada uno tiene una mentalidad de cada cosa, referencia a los Hippies
** Pag. 31 parrafo 3
*** Para que si estamos haciendo cosas peores causadas por un individualismo e intereses propios
** Pag. 31 parrafo 4
*** La gente muy apegada terminan así muchas veces y la musica es muy poderosa para identificar o identificarse con personalidades. 
* PROYECTO PEGASUS
** Pag. 33 parrafo 1 
*** La ciencia permite los viajes en ESPACIO tiempo que solo se da con una tecnología que solo se da en la tierra, requere dos distancias muy largas o dos velocidades rapidas para poder viajar una distancia mas rapido o mas larga que la anterior. Eso sería afectado por el movimiento al que estaria sometido.
** Pag. 33 parrafo 2
*** No es tan ciencia ficción como lo pintan, es algo mas de entender que si a una escala mayor, mayor masa se acelera a grandes velocidades cambiará su energía de la formula E=mc**2
** Pag. 33 parrafo 3
*** La teoria de la conspiración es una posible verdad o una posible mentira
** Pag. 33 parrafo 4
*** Aparte de la maquina del tiempo y viajar en el tiempo con unas leyes fisicas no con ciencia ficción, no crearía paradojas por que a partir de que fue creada la maquina del tiempo no se podría viajar al pasado, sería viajar a dos presentes en diferentes lugares y como el tiempo es relativo según la fisica con diferente tiempo, lo que sería posible sería viajar de un punto a otro con diferentes tiempos en diferentes momentos haciendo escala de un momento a otro

** Pag. 33 y 34 
*** Esa en una consecuencia de tomar una desición que anula a la otra
** Pag. 34 parrafo 2
*** El destino de uno es el destino de todos, si uno cambia, cambia todo como el caos
** Pag. 34 parrafo 3
*** El destino es el destino, pasará lo que va a pasar como en la máquina del tiempo de HG Wells que viajan al pasado para que no se muera la novia y cada vez que viaja y encuentra una solución para la enfermedad, siempre acaba muriendose.
** Pag. 34 y 35
*** Es mejor modificar lo que se pueda antes de un futuro destructivo para que destruya lo que no se pueda modificar, todo es un cambio constante acompañado de una predicción que es la que nos dice que debemos esperar para mejorar ó mantener.
* ORDEN DEL TIEMPO SOLAR
** pag. 36 parrafo 1
*** ser lider no deberia significar ser nada por que todos somos iguales ante la ley (algo lo que todo estamos sometidos) y tenemos iguales derechos (algo que nos defiendo) (si hay algo que nos defiende  y hay algo que nos somete entonces no podemos someter a alguien por que hay algo que defiende antes de someter los derechos)
** pag. 36 parrafo 2
*** cuando algo no es sostenible se añaden cosas como lo anterior dicho, cada uno decide  que hace con cada uno. la supremacia espritial parte de intereses propios lo cual se contradice con no mas placeres ya que estaria viviendo en un mundo placentero 
** pag. 36 parrafo 3
*** si se refiere con seres a los cuerpos celestes y con obserban se refieren a nos orbitan todo el tiempo ,  trasportandos a otros mundos se refiere a que estamos en un ciclo que tiene principio y fin trasmitinedo de genración en genración y que lo nos trasporta es el conocimineto y ideologias en las generaciones
** pag. 36 y 37
*** un texto cifrado no estan facil de comprender o dar referncias
** pag. 37 parrafo 2
*** se entiende que ezequiel no apoyaba al modelo de sociedad actual  estar lejos de la civilzacion como algunos otros con algunas otras idiologias parecidas que no estan conformes  
** pag. 37 parrafo 3
*** ... encaja con el perfil pero como todo es una supocision pero cada perosna es diferente y una supocison es una idea que no es cierta o lo puede ser por suerte y esto no es una razón para juzgar a los demas
** pag. 37 parrafo 4
*** no nos estan ocultando nada ... porque hasta que algo no es demostrado ,es encontrado o liberado no es debatible,  demsotrable o contradecible
* EXTRAÑO RITUAL
